sonar.projectKey=ifs24056-pabwe2026-nextjs
sonar.projectName=ifs24056-pabwe2026-nextjs

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,dist/**,src/app/**,src/setupTests.ts,src/testUtils.tsx,src/navMock.ts,src/lib/types.ts,**/*.test.ts,**/*.test.tsx